### ISSUE TITLE
Any guide for applying electron patches?

### ISSUE THREAD

**Issue by girish0x0** [noelex/v8dasm#1]
Hello, could you please help with applying electron patches or share any guide ?
thank you

**Comment by blksmr** [comment]
Hi, did you succeeded if so can you share how you did that please ?

**Comment by j4k0xb** [comment]
There's no need to apply electron patches as they don't affect the bytecode/serialization
Only additional required flag is pointer compression: https://github.com/j4k0xb/View8#building-the-disassembler

**Comment by blksmr** [comment]
> There's no need to apply electron patches as they don't affect the bytecode/serialization Only additional required flag is pointer compression: https://github.com/j4k0xb/View8#building-the-disassembler

Ty for replying i tried to follow the same guide as in v8dasm for v8 8.7.220.25 (which should be compatible with 8.7.220.31 cuz minor changes).
But i get weird errors with ninja building v8 sometimes error with objects.cc file (no error output only a failed result `ninja: build stopped: subcommand failed.` and sometimes due to errors related to the use of the offsetof macro on non-standard-layout types, which is not allowed by the C++ standard.
 `In file included from ../../src/init/setup-isolate-full.cc:8:
In file included from ../..\src/debug/debug-evaluate.h:11:
In file included from ../..\src/debug/debug-frames.h:10:
../..\src/deoptimizer/deoptimizer.h(511,38): error: offset of on non-standard-layout type 'v8::internal::Deoptimizer' [-Werror,-Winvalid-offsetof]
  static int input_offset() { return offsetof` an and Deoptimizer class.
  
  Do you have any idea of why i'm having this issue ?
  I'm using VS 2019
  
  
  Edit : 
  Replace offsetof by OFFSET_OF in deoptimier file

**Comment by girish0x0** [comment]
Hello @blksmr  Do you still need to decompile the v8 file?

**Comment by girish0x0** [comment]
thank you @j4k0xb
